spring:
  application:
    name: fall-festival-server

server:
  address: ${SERVER_ADDRESS:127.0.0.1}
  port: ${SERVER_PORT:8080}
  error:
    include-message: never
    include-stacktrace: never
    include-binding-errors: never
