package dev.espero.festival.domain;

/** Minimal action vocabulary; operational integrations add values when implemented. */
public enum AdminAuditAction {
    CROWDING_UPDATED,
    NOTICE_CREATED,
    NOTICE_UPDATED,
    NOTICE_DELETED,
    GOODS_AVAILABILITY_UPDATED,
    GOODS_IMAGE_UPLOADED,
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,
    LOVE_SEEDED,
    LOVE_INVITATION_REISSUED,
    LOVE_REPORTS_VIEWED,
    LOVE_REPORT_VIEWED,
    LOVE_LETTER_BLOCKED,
    LOVE_PARTICIPANT_RESTRICTED,
    LOVE_PARTICIPANT_UNRESTRICTED,
    LOVE_CONFIGURED,
    LOVE_ENABLED_CHANGED
}
